### ISSUE TITLE
New Feature Recommendation

### ISSUE THREAD

**Issue by arushgupta123** [JasPradhan/AI-Mario-Game#1]
@JasPradhan, you could add HTML. Then, with the help fo GitHub pages you could make this a website

**Comment by JasPradhan** [comment]
@arushgupta123 i have already made this an website long ago,
here is the link - 
https://jaspradhan.github.io/AI-Mario-Game/

**Comment by JasPradhan** [comment]
if you waqnt to play it

**Comment by arushgupta123** [comment]
ok
